### PR TITLE
WIP: Improve Docker setup

### PR DESCRIPTION
**Pull request by srisankethu**

### CODE REVIEW

**Comment by pedrouid** [comment]
Hi @srisankethu, thanks for the PR. Going to test this today. Meanwhile could you please also include the README changes to describe the Docker setup and other Make commands. If this works similarly to `py-walletconnect-bridge` setup then you should be able to copy&paste it into your branch.

**Comment by srisankethu** [comment]
@pedrouid Great! I will make complete the PR and make an update.

**Comment by srisankethu** [comment]
@pedrouid I am having issues and would like withdraw from this issue.

I am having issues of using yarn under corporate proxy and restrictions. Changed the settings but still unable to connect.

**Comment by pedrouid** [comment]
Hey @srisankethu, we can switch to NPM, that's totally fine. Just delete the `yarn.lock` file and run `npm install` to generate the `package-lock.json`.

**Comment by srisankethu** [comment]
@pedrouid Sorry, but I would like to drop this here. Thank you.

**Pull request closed without merging**
